apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: user-service
data:
  APP_ENV: "production"
  SERVICE_NAME: "user-service"
  DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@user-service-postgres-rw.user-service.svc.cluster.local:5432/user-service"
